const fetch = require('node-fetch');

let handler = async ({ m, bot, query, command }) => {
  const suggest = "Type the command along with the prompt 🥺";

  if (!query) {
    await bot.sendMessage(m.chat.id, suggest);
    return;
  }

  try {
    const res = await (await fetch('https://lexica.art/api/v1/search?q=' + query)).json();
    const randm = res.images;
    const resul = randm[Math.floor(Math.random() * randm.length)]; // Pick a random image from the array

    // Wait message to indicate the bot is processing the request
    await bot.sendMessage(m.chat.id, "⏳ Please wait, generating image...");

    const maker = "Generated by Lexica"; // Add this line before using 'maker'

    // Send the generated image to the user
    await bot.sendPhoto(m.chat.id, resul.src, {
      caption: `${maker}\nCreative: ${resul.prompt}\n\n[𝙿𝙾𝚆𝙴𝚁𝙴𝙳 𝙱𝚈 © 𝙼𝙴𝙶𝙰-𝙰𝙸]`
    });

  } catch (error) {
    console.error('Error generating image:', error);
    await bot.sendMessage(m.chat.id, "❌ An error occurred while generating the image. Please try again later.");
  }
};

module.exports = handler;
