import fetch from 'node-fetch';

let handler = async (m, { bot, text, command }) => {
  const suggest = "Type the command along with the prompt 🥺";

  if (!text) {
    await bot.sendMessage(m.chat.id, suggest);
    return;
  }

  try {
    const res = await (await fetch('https://lexica.art/api/v1/search?q=' + text)).json();
    const randm = res.images;
    const resul = randm[Math.floor(Math.random() * randm.length)]; // Pick a random image from the array

    // Wait message to indicate the bot is processing the request
    await bot.sendMessage(m.chat.id, "⏳ Please wait, generating image...");

    const maker = "*Generated by Lexica*"; // Add this line before using 'maker'

    // Send the generated image to the user
    await bot.sendPhoto(m.chat.id, resul.src, {
      caption: `${maker}\n*Creative:* ${resul.prompt}\n\n[Powered by Lexica](https://whatsapp.com/channel/0029VagJIAr3bbVBCpEkAM07)`
    });

  } catch (error) {
    console.error('Error generating image:', error);
    await bot.sendMessage(m.chat.id, "❌ An error occurred while generating the image. Please try again later.");
  }
};

handler.help = ["lexica"];
handler.tags = ['ai'];
handler.command = ["lexica"];

export default handler;
